(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["blog_$slug"],{

/***/ "./src/routes/blog/[slug].svelte":
/*!***************************************!*\
  !*** ./src/routes/blog/[slug].svelte ***!
  \***************************************/
/*! exports provided: default, preload */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preload", function() { return preload; });
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _utils_date__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../utils/date */ "./src/utils/date.js");
/* src/routes/blog/[slug].svelte generated by Svelte v3.29.4 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];

const file = "src/routes/blog/[slug].svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-d1l9nt-style";
	style.textContent = "article.svelte-d1l9nt{padding:4rem;margin:0 auto;max-width:1080px}article.svelte-d1l9nt section + section{border-top:1px solid red;padding-top:1rem;margin-top:2rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiW3NsdWddLnN2ZWx0ZSIsInNvdXJjZXMiOlsiW3NsdWddLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9J21vZHVsZSc+XG5cdGV4cG9ydCBhc3luYyBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG5cdCAgICB0cnkge1xuICAgICAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgYmxvZy8ke3BhcmFtcy5zbHVnfS5qc29uYCk7XG5cbiAgICAgICAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgICAgICAgICAgY29uc29sZS5lcnJvcihgZXJyb3IgZmV0Y2hpbmcgcG9zdCBkYXRhIGZvciAke3BhcmFtcy5zbHVnfSB3aXRoIHN0YXR1cyAke3Jlcy5zdGF0dXN9YCk7XG4gICAgICAgICAgICAgICAgcmV0dXJuIHtwb3N0OiBudWxsfTtcbiAgICAgICAgICAgIH1cblxuICAgICAgICAgICAgY29uc3QgcG9zdCA9IGF3YWl0IHJlcy5qc29uKCk7XG4gICAgICAgICAgICByZXR1cm4ge3Bvc3R9O1xuXHRcdH0gY2F0Y2ggKGUpIHtcblx0ICAgICAgICBjb25zb2xlLmVycm9yKGB1bmtub3duIGVycm9yIGZldGNoaW5nIHBvc3QgZGF0YSBmb3IgJHtwYXJhbXMuc2x1Z31gLCBlKTtcblx0ICAgICAgICByZXR1cm4ge3Bvc3Q6IG51bGx9O1xuXHRcdH1cblx0fVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG5cdGV4cG9ydCBsZXQgcG9zdDtcblx0aW1wb3J0IHtwcmludF9kYXRlfSBmcm9tICcuLi8uLi91dGlscy9kYXRlJztcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgYXJ0aWNsZSB7XG4gICAgICAgIHBhZGRpbmc6IDRyZW07XG4gICAgICAgIG1hcmdpbjogMCBhdXRvO1xuICAgICAgICBtYXgtd2lkdGg6IDEwODBweDtcbiAgICB9XG4gICAgYXJ0aWNsZSA6Z2xvYmFsKHNlY3Rpb24gKyBzZWN0aW9uKSB7XG4gICAgICAgIGJvcmRlci10b3A6IDFweCBzb2xpZCByZWQ7XG4gICAgICAgIHBhZGRpbmctdG9wOiAxcmVtO1xuICAgICAgICBtYXJnaW4tdG9wOiAycmVtO1xuICAgIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPntwb3N0LnRpdGxlfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48YXJ0aWNsZT5cbiAgICA8aGVhZGVyPlxuICAgICAgICA8aDI+e3Bvc3QudGl0bGV9PC9oMj5cbiAgICAgICAgPHRpbWU+e3ByaW50X2RhdGUobmV3IERhdGUocG9zdC5kYXRlKSl9PC90aW1lPlxuICAgIDwvaGVhZGVyPlxuXHR7QGh0bWwgcG9zdC5odG1sfVxuPC9hcnRpY2xlPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQXlCSSxPQUFPLGNBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxJQUFJLENBQ2IsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsU0FBUyxDQUFFLE1BQU0sQUFDckIsQ0FBQyxBQUNELHFCQUFPLENBQUMsQUFBUSxpQkFBaUIsQUFBRSxDQUFDLEFBQ2hDLFVBQVUsQ0FBRSxHQUFHLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FDekIsV0FBVyxDQUFFLElBQUksQ0FDakIsVUFBVSxDQUFFLElBQUksQUFDcEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let article;
	let header;
	let h2;
	let t1_value = /*post*/ ctx[0].title + "";
	let t1;
	let t2;
	let time;
	let t3_value = Object(_utils_date__WEBPACK_IMPORTED_MODULE_1__["print_date"])(new Date(/*post*/ ctx[0].date)) + "";
	let t3;
	let t4;
	let html_tag;
	let raw_value = /*post*/ ctx[0].html + "";
	document.title = title_value = /*post*/ ctx[0].title;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			time = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("time");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1uty71u\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "HEADER", {});
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H2", {});
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, t1_value);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			time = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "TIME", {});
			var time_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(time);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(time_nodes, t3_value);
			time_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 43, 8, 980);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(time, file, 44, 8, 1010);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 42, 4, 963);
			html_tag = new svelte_internal__WEBPACK_IMPORTED_MODULE_0__["HtmlTag"](null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-d1l9nt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 41, 0, 949);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, article, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, time);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(time, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			html_tag.m(raw_value, article);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*post*/ 1 && title_value !== (title_value = /*post*/ ctx[0].title)) {
				document.title = title_value;
			}

			if (dirty & /*post*/ 1 && t1_value !== (t1_value = /*post*/ ctx[0].title + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			if (dirty & /*post*/ 1 && t3_value !== (t3_value = Object(_utils_date__WEBPACK_IMPORTED_MODULE_1__["print_date"])(new Date(/*post*/ ctx[0].date)) + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*post*/ 1 && raw_value !== (raw_value = /*post*/ ctx[0].html + "")) html_tag.p(raw_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(article);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

async function preload({ params, query }) {
	try {
		const res = await this.fetch(`blog/${params.slug}.json`);

		if (!res.ok) {
			console.error(`error fetching post data for ${params.slug} with status ${res.status}`);
			return { post: null };
		}

		const post = await res.json();
		return { post };
	} catch(e) {
		console.error(`unknown error fetching post data for ${params.slug}`, e);
		return { post: null };
	}
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("U5Bslugu5D", slots, []);
	let { post } = $$props;
	const writable_props = ["post"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<U5Bslugu5D> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("post" in $$props) $$invalidate(0, post = $$props.post);
	};

	$$self.$capture_state = () => ({ preload, post, print_date: _utils_date__WEBPACK_IMPORTED_MODULE_1__["print_date"] });

	$$self.$inject_state = $$props => {
		if ("post" in $$props) $$invalidate(0, post = $$props.post);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [post];
}

class U5Bslugu5D extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-d1l9nt-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { post: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "U5Bslugu5D",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*post*/ ctx[0] === undefined && !("post" in props)) {
			console_1.warn("<U5Bslugu5D> was created without expected prop 'post'");
		}
	}

	get post() {
		throw new Error("<U5Bslugu5D>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set post(value) {
		throw new Error("<U5Bslugu5D>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (U5Bslugu5D);


/***/ }),

/***/ "./src/utils/date.js":
/*!***************************!*\
  !*** ./src/utils/date.js ***!
  \***************************/
/*! exports provided: print_date */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "print_date", function() { return print_date; });
function print_date(d) {
    return new Intl.DateTimeFormat('de-DE', {year: 'numeric', month: '2-digit', day: '2-digit'}).format(d);
}


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2Jsb2cvW3NsdWddLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvdXRpbHMvZGF0ZS5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFxQjZDOzs7Ozs7Ozs7Ozs7Ozs7O3lCQXNCaEMsR0FBSSxJQUFDLEtBQUs7Ozs7Z0JBQ1IsOERBQVUsS0FBSyxJQUFJLFVBQUMsR0FBSSxJQUFDLElBQUk7Ozs7MEJBRXBDLEdBQUksSUFBQyxJQUFJO3lDQVJSLEdBQUksSUFBQyxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FFQUFWLEdBQUksSUFBQyxLQUFLOzs7OytEQUtOLEdBQUksSUFBQyxLQUFLO3NEQUNSLDhEQUFVLEtBQUssSUFBSSxVQUFDLEdBQUksSUFBQyxJQUFJO2lFQUVwQyxHQUFJLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2VBN0NNLE9BQU8sR0FBRyxNQUFNLEVBQUUsS0FBSzs7UUFFNUIsR0FBRyxTQUFTLElBQUksQ0FBQyxLQUFLLFNBQVMsTUFBTSxDQUFDLElBQUk7O09BRTNDLEdBQUcsQ0FBQyxFQUFFO0dBQ1AsT0FBTyxDQUFDLEtBQUssaUNBQWlDLE1BQU0sQ0FBQyxJQUFJLGdCQUFnQixHQUFHLENBQUMsTUFBTTtZQUMzRSxJQUFJLEVBQUUsSUFBSTs7O1FBR2hCLElBQUksU0FBUyxHQUFHLENBQUMsSUFBSTtXQUNuQixJQUFJO1NBQ2IsQ0FBQztFQUNILE9BQU8sQ0FBQyxLQUFLLHlDQUF5QyxNQUFNLENBQUMsSUFBSSxJQUFJLENBQUM7V0FDOUQsSUFBSSxFQUFFLElBQUk7Ozs7Ozs7T0FNZixJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDcEJoQjtBQUFBO0FBQU87QUFDUCw2Q0FBNkMsa0RBQWtEO0FBQy9GIiwiZmlsZSI6ImQxNGNlOTBlYmUxZjdiZWY4MGU4L2Jsb2dfJHNsdWcuYmxvZ18kc2x1Zy5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQgY29udGV4dD0nbW9kdWxlJz5cblx0ZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcblx0ICAgIHRyeSB7XG4gICAgICAgICAgICBjb25zdCByZXMgPSBhd2FpdCB0aGlzLmZldGNoKGBibG9nLyR7cGFyYW1zLnNsdWd9Lmpzb25gKTtcblxuICAgICAgICAgICAgaWYgKCFyZXMub2spIHtcbiAgICAgICAgICAgICAgICBjb25zb2xlLmVycm9yKGBlcnJvciBmZXRjaGluZyBwb3N0IGRhdGEgZm9yICR7cGFyYW1zLnNsdWd9IHdpdGggc3RhdHVzICR7cmVzLnN0YXR1c31gKTtcbiAgICAgICAgICAgICAgICByZXR1cm4ge3Bvc3Q6IG51bGx9O1xuICAgICAgICAgICAgfVxuXG4gICAgICAgICAgICBjb25zdCBwb3N0ID0gYXdhaXQgcmVzLmpzb24oKTtcbiAgICAgICAgICAgIHJldHVybiB7cG9zdH07XG5cdFx0fSBjYXRjaCAoZSkge1xuXHQgICAgICAgIGNvbnNvbGUuZXJyb3IoYHVua25vd24gZXJyb3IgZmV0Y2hpbmcgcG9zdCBkYXRhIGZvciAke3BhcmFtcy5zbHVnfWAsIGUpO1xuXHQgICAgICAgIHJldHVybiB7cG9zdDogbnVsbH07XG5cdFx0fVxuXHR9XG48L3NjcmlwdD5cblxuPHNjcmlwdD5cblx0ZXhwb3J0IGxldCBwb3N0O1xuXHRpbXBvcnQge3ByaW50X2RhdGV9IGZyb20gJy4uLy4uL3V0aWxzL2RhdGUnO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgICBhcnRpY2xlIHtcbiAgICAgICAgcGFkZGluZzogNHJlbTtcbiAgICAgICAgbWFyZ2luOiAwIGF1dG87XG4gICAgICAgIG1heC13aWR0aDogMTA4MHB4O1xuICAgIH1cbiAgICBhcnRpY2xlIDpnbG9iYWwoc2VjdGlvbiArIHNlY3Rpb24pIHtcbiAgICAgICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHJlZDtcbiAgICAgICAgcGFkZGluZy10b3A6IDFyZW07XG4gICAgICAgIG1hcmdpbi10b3A6IDJyZW07XG4gICAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+e3Bvc3QudGl0bGV9PC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxhcnRpY2xlPlxuICAgIDxoZWFkZXI+XG4gICAgICAgIDxoMj57cG9zdC50aXRsZX08L2gyPlxuICAgICAgICA8dGltZT57cHJpbnRfZGF0ZShuZXcgRGF0ZShwb3N0LmRhdGUpKX08L3RpbWU+XG4gICAgPC9oZWFkZXI+XG5cdHtAaHRtbCBwb3N0Lmh0bWx9XG48L2FydGljbGU+XG4iLCJleHBvcnQgZnVuY3Rpb24gcHJpbnRfZGF0ZShkKSB7XG4gICAgcmV0dXJuIG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdkZS1ERScsIHt5ZWFyOiAnbnVtZXJpYycsIG1vbnRoOiAnMi1kaWdpdCcsIGRheTogJzItZGlnaXQnfSkuZm9ybWF0KGQpO1xufVxuIl0sInNvdXJjZVJvb3QiOiIifQ==