(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["blog_$slug"],{

/***/ "./src/routes/blog/[slug].svelte":
/*!***************************************!*\
  !*** ./src/routes/blog/[slug].svelte ***!
  \***************************************/
/*! exports provided: default, preload */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preload", function() { return preload; });
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _utils_date__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../utils/date */ "./src/utils/date.js");
/* src/routes/blog/[slug].svelte generated by Svelte v3.16.7 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];

const file = "src/routes/blog/[slug].svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-zrn93i-style";
	style.textContent = "article.svelte-zrn93i{padding:4rem;margin:0 auto;max-width:1080px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiW3NsdWddLnN2ZWx0ZSIsInNvdXJjZXMiOlsiW3NsdWddLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9J21vZHVsZSc+XG5cdGV4cG9ydCBhc3luYyBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG5cdCAgICB0cnkge1xuICAgICAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgYmxvZy8ke3BhcmFtcy5zbHVnfS5qc29uYCk7XG5cbiAgICAgICAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgICAgICAgICAgY29uc29sZS5lcnJvcihgZXJyb3IgZmV0Y2hpbmcgcG9zdCBkYXRhIGZvciAke3BhcmFtcy5zbHVnfSB3aXRoIHN0YXR1cyAke3Jlcy5zdGF0dXN9YCk7XG4gICAgICAgICAgICAgICAgcmV0dXJuIHtwb3N0OiBudWxsfTtcbiAgICAgICAgICAgIH1cblxuICAgICAgICAgICAgY29uc3QgcG9zdCA9IGF3YWl0IHJlcy5qc29uKCk7XG4gICAgICAgICAgICByZXR1cm4ge3Bvc3R9O1xuXHRcdH0gY2F0Y2ggKGUpIHtcblx0ICAgICAgICBjb25zb2xlLmVycm9yKGB1bmtub3duIGVycm9yIGZldGNoaW5nIHBvc3QgZGF0YSBmb3IgJHtwYXJhbXMuc2x1Z31gLCBlKTtcblx0ICAgICAgICByZXR1cm4ge3Bvc3Q6IG51bGx9O1xuXHRcdH1cblx0fVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG5cdGV4cG9ydCBsZXQgcG9zdDtcblx0aW1wb3J0IHtwcmludF9kYXRlfSBmcm9tICcuLi8uLi91dGlscy9kYXRlJztcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgYXJ0aWNsZSB7XG4gICAgICAgIHBhZGRpbmc6IDRyZW07XG4gICAgICAgIG1hcmdpbjogMCBhdXRvO1xuICAgICAgICBtYXgtd2lkdGg6IDEwODBweDtcbiAgICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT57cG9zdC50aXRsZX08L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGFydGljbGU+XG4gICAgPGhlYWRlcj5cbiAgICAgICAgPGgyPntwb3N0LnRpdGxlfTwvaDI+XG4gICAgICAgIDx0aW1lPntwcmludF9kYXRlKG5ldyBEYXRlKHBvc3QuZGF0ZSkpfTwvdGltZT5cbiAgICA8L2hlYWRlcj5cblx0e0BodG1sIHBvc3QuaHRtbH1cbjwvYXJ0aWNsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF5QkksT0FBTyxjQUFDLENBQUMsQUFDTCxPQUFPLENBQUUsSUFBSSxDQUNiLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUNkLFNBQVMsQ0FBRSxNQUFNLEFBQ3JCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let article;
	let header;
	let h2;
	let t1_value = /*post*/ ctx[0].title + "";
	let t1;
	let t2;
	let time;
	let t3_value = Object(_utils_date__WEBPACK_IMPORTED_MODULE_1__["print_date"])(new Date(/*post*/ ctx[0].date)) + "";
	let t3;
	let t4;
	let html_tag;
	let raw_value = /*post*/ ctx[0].html + "";
	document.title = title_value = /*post*/ ctx[0].title;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			time = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("time");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h();
		},
		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "HEADER", {});
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H2", {});
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, t1_value);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			time = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "TIME", {});
			var time_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(time);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(time_nodes, t3_value);
			time_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 38, 8, 845);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(time, file, 39, 8, 875);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 37, 4, 828);
			html_tag = new svelte_internal__WEBPACK_IMPORTED_MODULE_0__["HtmlTag"](raw_value, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-zrn93i");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 36, 0, 814);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, article, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, time);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(time, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			html_tag.m(article);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*post*/ 1 && title_value !== (title_value = /*post*/ ctx[0].title)) {
				document.title = title_value;
			}

			if (dirty & /*post*/ 1 && t1_value !== (t1_value = /*post*/ ctx[0].title + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			if (dirty & /*post*/ 1 && t3_value !== (t3_value = Object(_utils_date__WEBPACK_IMPORTED_MODULE_1__["print_date"])(new Date(/*post*/ ctx[0].date)) + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*post*/ 1 && raw_value !== (raw_value = /*post*/ ctx[0].html + "")) html_tag.p(raw_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(article);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

async function preload({ params, query }) {
	try {
		const res = await this.fetch(`blog/${params.slug}.json`);

		if (!res.ok) {
			console.error(`error fetching post data for ${params.slug} with status ${res.status}`);
			return { post: null };
		}

		const post = await res.json();
		return { post };
	} catch(e) {
		console.error(`unknown error fetching post data for ${params.slug}`, e);
		return { post: null };
	}
}

function instance($$self, $$props, $$invalidate) {
	let { post } = $$props;
	const writable_props = ["post"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<U5Bslugu5D> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ("post" in $$props) $$invalidate(0, post = $$props.post);
	};

	$$self.$capture_state = () => {
		return { post };
	};

	$$self.$inject_state = $$props => {
		if ("post" in $$props) $$invalidate(0, post = $$props.post);
	};

	return [post];
}

class U5Bslugu5D extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-zrn93i-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { post: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "U5Bslugu5D",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || ({});

		if (/*post*/ ctx[0] === undefined && !("post" in props)) {
			console_1.warn("<U5Bslugu5D> was created without expected prop 'post'");
		}
	}

	get post() {
		throw new Error("<U5Bslugu5D>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set post(value) {
		throw new Error("<U5Bslugu5D>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (U5Bslugu5D);


/***/ }),

/***/ "./src/utils/date.js":
/*!***************************!*\
  !*** ./src/utils/date.js ***!
  \***************************/
/*! exports provided: print_date */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "print_date", function() { return print_date; });
function print_date(d) {
    return new Intl.DateTimeFormat('de-DE', {year: 'numeric', month: '2-digit', day: '2-digit'}).format(d);
}


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2Jsb2cvW3NsdWddLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvdXRpbHMvZGF0ZS5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFFNEM7Ozs7Ozs7Ozs7Ozs7Ozs7eUJBb0MvQixHQUFJLElBQUMsS0FBSzs7OztnQkFDUiw4REFBVSxLQUFLLElBQUksVUFBQyxHQUFJLElBQUMsSUFBSTs7OzswQkFFcEMsR0FBSSxJQUFDLElBQUk7eUNBUlIsR0FBSSxJQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FFQUFWLEdBQUksSUFBQyxLQUFLOzs7OytEQUtOLEdBQUksSUFBQyxLQUFLO3NEQUNSLDhEQUFVLEtBQUssSUFBSSxVQUFDLEdBQUksSUFBQyxJQUFJO2lFQUVwQyxHQUFJLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2VBeENNLE9BQU8sR0FBRyxNQUFNLEVBQUUsS0FBSzs7UUFFNUIsR0FBRyxTQUFTLElBQUksQ0FBQyxLQUFLLFNBQVMsTUFBTSxDQUFDLElBQUk7O09BRTNDLEdBQUcsQ0FBQyxFQUFFO0dBQ1AsT0FBTyxDQUFDLEtBQUssaUNBQWlDLE1BQU0sQ0FBQyxJQUFJLGdCQUFnQixHQUFHLENBQUMsTUFBTTtZQUMzRSxJQUFJLEVBQUUsSUFBSTs7O1FBR2hCLElBQUksU0FBUyxHQUFHLENBQUMsSUFBSTtXQUNuQixJQUFJO1NBQ2IsQ0FBQztFQUNILE9BQU8sQ0FBQyxLQUFLLHlDQUF5QyxNQUFNLENBQUMsSUFBSSxJQUFJLENBQUM7V0FDOUQsSUFBSSxFQUFFLElBQUk7Ozs7O09BYmYsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNEaEI7QUFBQTtBQUFPO0FBQ1AsNkNBQTZDLGtEQUFrRDtBQUMvRiIsImZpbGUiOiI1MmJiMjA0NWVkZGY3NTRmMjRiYy9ibG9nXyRzbHVnLmJsb2dfJHNsdWcuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9J21vZHVsZSc+XG5cdGV4cG9ydCBhc3luYyBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG5cdCAgICB0cnkge1xuICAgICAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgYmxvZy8ke3BhcmFtcy5zbHVnfS5qc29uYCk7XG5cbiAgICAgICAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgICAgICAgICAgY29uc29sZS5lcnJvcihgZXJyb3IgZmV0Y2hpbmcgcG9zdCBkYXRhIGZvciAke3BhcmFtcy5zbHVnfSB3aXRoIHN0YXR1cyAke3Jlcy5zdGF0dXN9YCk7XG4gICAgICAgICAgICAgICAgcmV0dXJuIHtwb3N0OiBudWxsfTtcbiAgICAgICAgICAgIH1cblxuICAgICAgICAgICAgY29uc3QgcG9zdCA9IGF3YWl0IHJlcy5qc29uKCk7XG4gICAgICAgICAgICByZXR1cm4ge3Bvc3R9O1xuXHRcdH0gY2F0Y2ggKGUpIHtcblx0ICAgICAgICBjb25zb2xlLmVycm9yKGB1bmtub3duIGVycm9yIGZldGNoaW5nIHBvc3QgZGF0YSBmb3IgJHtwYXJhbXMuc2x1Z31gLCBlKTtcblx0ICAgICAgICByZXR1cm4ge3Bvc3Q6IG51bGx9O1xuXHRcdH1cblx0fVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG5cdGV4cG9ydCBsZXQgcG9zdDtcblx0aW1wb3J0IHtwcmludF9kYXRlfSBmcm9tICcuLi8uLi91dGlscy9kYXRlJztcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgYXJ0aWNsZSB7XG4gICAgICAgIHBhZGRpbmc6IDRyZW07XG4gICAgICAgIG1hcmdpbjogMCBhdXRvO1xuICAgICAgICBtYXgtd2lkdGg6IDEwODBweDtcbiAgICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT57cG9zdC50aXRsZX08L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGFydGljbGU+XG4gICAgPGhlYWRlcj5cbiAgICAgICAgPGgyPntwb3N0LnRpdGxlfTwvaDI+XG4gICAgICAgIDx0aW1lPntwcmludF9kYXRlKG5ldyBEYXRlKHBvc3QuZGF0ZSkpfTwvdGltZT5cbiAgICA8L2hlYWRlcj5cblx0e0BodG1sIHBvc3QuaHRtbH1cbjwvYXJ0aWNsZT5cbiIsImV4cG9ydCBmdW5jdGlvbiBwcmludF9kYXRlKGQpIHtcbiAgICByZXR1cm4gbmV3IEludGwuRGF0ZVRpbWVGb3JtYXQoJ2RlLURFJywge3llYXI6ICdudW1lcmljJywgbW9udGg6ICcyLWRpZ2l0JywgZGF5OiAnMi1kaWdpdCd9KS5mb3JtYXQoZCk7XG59XG4iXSwic291cmNlUm9vdCI6IiJ9